# Gopkg.toml example
#
# Refer to https:
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[constraint]]
  branch = "master"
  name = "bazil.org/fuse"

[[constraint]]
  name = "github.com/Azure/azure-storage-go"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/aristanetworks/goarista"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcd"

[[constraint]]
  branch = "master"
  name = "github.com/cespare/cp"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.0"

[[constraint]]
  name = "github.com/docker/docker"
  version = "1.13.1"

[[constraint]]
  branch = "master"
  name = "github.com/edsrzf/mmap-go"

[[constraint]]
  name = "github.com/elastic/gosigar"
  version = "0.8.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[constraint]]
  name = "github.com/gizak/termui"
  version = "2.2.0"

[[constraint]]
  name = "github.com/go-stack/stack"
  version = "1.7.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/snappy"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/golang-lru"

[[constraint]]
  branch = "master"
  name = "github.com/huin/goupnp"

[[constraint]]
  name = "github.com/jackpal/go-nat-pmp"
  version = "1.0.1"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/karalabe/hid"

[[constraint]]
  name = "github.com/mattn/go-colorable"
  version = "0.0.9"

[[constraint]]
  name = "github.com/naoina/toml"
  version = "0.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/peterh/liner"

[[constraint]]
  name = "github.com/prometheus/prometheus"
  version = "2.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/rcrowley/go-metrics"

[[constraint]]
  branch = "master"
  name = "github.com/rjeczalik/notify"

[[constraint]]
  branch = "master"
  name = "github.com/robertkrimen/otto"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/syndtr/goleveldb"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"

[[constraint]]
  name = "gopkg.in/fatih/set.v0"
  version = "0.1.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/karalabe/cookiejar.v2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/natefinch/npipe.v2"

[[constraint]]
  branch = "v3"
  name = "gopkg.in/olebedev/go-duktape.v3"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"

[prune]
  go-tests = true
  unused-packages = true
